global_options:
  freezed:freezed:
    runs_before:
      - hive_generator:hive_generator
      - type_register:type_register
  hive_generator:hive_generator:
    runs_before:
      - json_serializable:json_serializable

targets:
  $default:
    builders:
      type_register|type_register:
        options:
          output_path: lib/src/core/
