name: example
description: Example for type generator
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  
 hive_local_storage: ^1.0.10
  

dev_dependencies:
 
  flutter_lints: ^3.0.1
  build_runner: ^2.4.6
  type_register:
    path: ../
  
  hive_generator: ^2.0.1
